# Generated by Django 5.0.7 on 2026-09-14 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled dataset', max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('csv', 'CSV'), ('excel', 'Excel'), ('random', 'Random')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('area', 'Area'), ('spline', 'Spline'), ('line', 'Line'), ('bar', 'Bar')], max_length=10)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='chartdata.dataset')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='chartdata.series')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('series', 'date')},
            },
        ),
    ]
